### ISSUE TITLE
Capturing the button presses from a Razer Tartarus V2?

### ISSUE THREAD

**Issue by latenitefilms** [1kc/librazermacos#7]
Apologies in advance for a slightly off-topic issue.

I'm interested in using a Razer Tartarus V2 on macOS without any of the official Razer software, which is how I came across this awesome repo.

I've played around with this code, and it gives fantastic control in terms of changing all the LEDs on the Razer Tartarus V2 - great work!

However, I'm interested in how I can detect the button presses on a Razer Tartarus V2, without them triggering any keyboard buttons on macOS. It seems that, by default the Razer Tartarus V2 has a built-in layout that trigger normal keyboard button presses - whereas I'm hoping to trigger specific things when the buttons are pressed.

Is the main purpose of this repo to just concentrate on the LED controls - or are you planning to add the ability to change what the buttons do any some stage?

I'm completely new to Razer and Synapse, so apologies if I'm missing something obvious.

Any words of wisdom you can provide would be greatly appreciated. Thank you!

**Comment by edualm** [comment]
Hey - unfortunately for now the scope of this library is only color-related stuff. I

 don't think there are any plans to do what you want, as that's a completely different beast. :(

**Comment by latenitefilms** [comment]
No stress at all! Thanks for the fast reply!
